### ISSUE TITLE
german braille: hyphenation issues 10/23

### ISSUE THREAD

**Issue by mabo991** [sbsdev/sbs-hyphenation-tables#2]
The daisy-pipeline users of blista Marburg reported some hyphenation issues to me:

```
Aisha		Ai-sha			# not Ais-ha
Ananaseis	Ana-nas-eis		# not Anana-seis
Comicheft	Co-mic-heft		# not Com-icheft
dunkelmagenta	dun-kel-ma-gen-ta	# not Dunkelm-agenta
gedartet	ge-dar-tet		# not ged-artet
Rezeptidee	Re-zept-i-dee		# not Rezep-tidee
Tonassistent	Ton-as-sis-tent		# not To-nassistent
Vliespullover	Vlies-pul-l-over	# not Vlie-spullover
Wechselmodell	Wech-sel-mo-dell	# not Wechselm-odell
```

Is it enough to report this list of incorrectly hyphenated words or should I integrate it into some file in this project?

**Comment by egli** [comment]
> Is it enough to report this list of incorrectly hyphenated words or should I integrate it into some file in this project?

I haven't looked at this in ages, but I think the words need to be added to `src/main/resources/tables/trennfehler_gesamtliste.xml`.

A PR would be very welcome

**Comment by mabo991** [comment]
Okay, I will add them to this xml file and create a PR.

Just one question: Have I understood the xml structure correct so far?

```
<wort>
    <ss>abschiedsshow</ss> <--  complete word -->
    <rs>NEU</rs>  <--  always seems to be set to "NEU" ? -->
    <is>abschiedss-how</is>  <--  wrong hyphenation -->
    <so>ab-schieds-show</so>  <--  correct hyphenation -->
    <be/> <-- What's this? -->
    <da>28.07.2017</da> <-- Date of the report -->
  </wort>
```

**Comment by egli** [comment]
Hi @mabo991, I'm not sure who designed the format. All I know that I was not involved.

`rs` stands for Rechtschreibung. There still are hyphenation tables for the old spelling, but as far as I know the XML only contains hypenations for the new spelling, so, yes, always `Neu`

I have no idea what `be` is for

Yes the `da` stands for the date of the report (which is ignored by the import as far as I can tell)

I got all of above information from looking at `src/build/java/GenerateWhitelist.java`

Hope that helps

**Comment by mabo991** [comment]
Thank you!
I created a PR (https://github.com/sbsdev/sbs-hyphenation-tables/pull/3)
